name: py310
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=2.302=openblas
  - blas-devel=3.11.0=2_ha590de0_openblas
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h5py=3.15.1=nompi_py310hb7e4da9_101
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - keras=3.12.0=pyh753f3f9_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.11.0=2_h0adab6e_openblas
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.11.0=2_h2a8eebe_openblas
  - libclang13=21.1.6=default_ha2db4b5_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.2=hd9c3897_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=2_hd232482_openblas
  - liblapacke=3.11.0=2_hbb0e6ff_openblas
  - liblzma=5.8.1=h2466b09_2
  - libopenblas=0.3.30=pthreads_h877e47f_4
  - libpng=1.6.51=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - ml_dtypes=0.5.4=np2py310h7578f05_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nomkl=3.0=0
  - openblas=0.3.30=pthreads_h4a7f399_4
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - optree=0.18.0=py310he9f1925_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py310hfb50504_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py310h96c60bd_1
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - rich=14.2.0=pyhcf101f3_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py310h29418f3_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - attrs==25.4.0
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - filelock==3.19.1
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - fsspec==2025.9.0
      - idna==3.7
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - kaggle==1.7.4.5
      - markupsafe==2.1.5
      - mediapipe==0.10.21
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.23.5
      - opencv-contrib-python==4.7.0.72
      - opt-einsum==3.4.0
      - pi-heif==1.1.1
      - pillow-avif-plugin==1.5.2
      - protobuf==4.25.8
      - pycparser==2.23
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - roboflow==1.2.11
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sounddevice==0.5.3
      - sympy==1.14.0
      - text-unidecode==1.3
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - urllib3==2.5.0
      - webencodings==0.5.1
prefix: D:\Programs\miniconda3\envs\py310
